version: '3.8'

services:
  backend:
    build: ./backend
    container_name: resume-analyzer-backend
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FLASK_ENV=${FLASK_ENV:-production}
    volumes:
      - ./backend:/app
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: resume-analyzer-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always

networks:
  default:
    name: resume-analyzer-network
